### ISSUE TITLE
Install command issues

### ISSUE THREAD

**Issue by jkblgithub** [simplabs/ember-cli-simple-auth-cookie-store#4]
Hi,

I am on 0.1.4 of ember-cli. Tried installing with the:
`ember install:addon ember-cli-simple-auth-cookie-store`
 but I got the error:
**The specified command install:addon is invalid, for available options see ember help.**

I then tried the npm install, but when I issued the:
`ember generate ember-cli-simple-auth-cookie-store` command, I got the following:
cookie-store
version: 0.1.4
valid watchman found, version: [3.0.0]
installing
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
  not-cached git://github.com/simplabs/ember-simple-auth-component.git#0.7.3
  resolved git://github.com/simplabs/ember-simple-auth-component.git#0.7.3
  conflict Unable to find suitable version for ember-simple-auth
    1) ember-simple-auth 0.6.7
    2) ember-simple-auth 0.7.3
[?] Answer: 2
Installed browser packages via Bower.

How should I proceed please?

**Comment by marcoow** [comment]
You successfully installed Ember Simple Auth Cookie Store - everything's alright.

**Comment by jkblgithub** [comment]
Thank you!
